require_relative 'spec_helper'
require 'rack'
require 'rack/lint'
require 'rack/mock_request'

describe 'Streaming EPUB output' do
  # Only responds to `<<`, like a socket wrapper or a Rack stream would
  class ChunkCollector
    attr_reader :chunks

    def initialize
      @chunks = []
    end

    def <<(data)
      @chunks << data.dup
      self
    end

    def string
      @chunks.join
    end
  end

  def build_book
    book = GEPUB::Book.new
    book.identifier = 'http://example.jp/streaming'
    book.title = 'Streamed book'
    book.language = 'en'
    book.ordered do
      book.add_item('text/chap1.xhtml', content: StringIO.new(chapter('Chapter 1'))).toc_text('Chapter 1')
      book.add_item('text/chap2.xhtml', content: StringIO.new(chapter('Chapter 2'))).toc_text('Chapter 2')
    end
    book.add_item('img/image1.jpg', content: (@fixtures_directory / 'testdata/image1.jpg').open('rb')).cover_image
    book
  end

  def chapter(title)
    <<~XHTML
      <html xmlns="http://www.w3.org/1999/xhtml"><head><title>#{title}</title></head>
      <body><h1>#{title}</h1><p>#{'Some text. ' * 500}</p></body></html>
    XHTML
  end

  def expect_valid_epub(bytes)
    epub_file = @temporary_directory / 'streamed.epub'
    epub_file.binwrite(bytes)
    epubcheck(epub_file)

    parsed = GEPUB::Book.parse(StringIO.new(bytes))
    expect(parsed.items.values.map(&:href)).to include('text/chap1.xhtml', 'text/chap2.xhtml', 'img/image1.jpg')
  end

  describe '#write_epub' do
    it 'writes a valid EPUB into an object which only responds to <<', :uses_temporary_directory do
      sink = ChunkCollector.new
      expect(build_book.write_epub(sink)).to equal(sink)
      expect(sink.chunks.size).to be > 1 # it got written piecewise, not as one blob
      expect_valid_epub(sink.string)
    end

    it 'writes a valid EPUB into an object which only responds to write', :uses_temporary_directory do
      out = Object.new
      buf = +''
      out.define_singleton_method(:write) { |data| buf << data; data.bytesize }
      build_book.write_epub(out)
      expect_valid_epub(buf)
    end

    it 'produces the same EPUB as generate_epub_stream' do
      book = build_book
      book.lastmodified = '2026-10-08T10:00:00Z' # otherwise the timestamps in the ZIP differ
      streamed = book.generate_epub_stream.string
      expect(streamed.encoding).to eq(Encoding::BINARY)
      expect(book.write_epub(ChunkCollector.new).string).to eq(streamed)
    end
  end

  describe '#to_rack_body' do
    it 'does not write anything until iterated over, but runs cleanup right away' do
      book = build_book
      expect(book).not_to receive(:write_to_epub_container)
      book.to_rack_body
      expect(book.items.values.map(&:href)).to include('nav.xhtml') # generated by cleanup
    end

    it 'yields a valid EPUB in binary chunks', :uses_temporary_directory do
      chunks = []
      build_book.to_rack_body.each { |chunk| chunks << chunk.dup }
      expect(chunks).to all(satisfy { |c| c.encoding == Encoding::BINARY })
      expect_valid_epub(chunks.join)
    end

    it 'can be served as a Rack response body', :uses_temporary_directory do
      book = build_book
      app = ->(_env) { [200, {'content-type' => 'application/epub+zip'}, book.to_rack_body] }
      response = Rack::MockRequest.new(Rack::Lint.new(app)).get('/book.epub')

      expect(response.status).to eq(200)
      expect_valid_epub(response.body)
    end

    it 'raises from each when the EPUB cannot be written' do
      book = build_book
      book.add_item('text/what?.xhtml', content: StringIO.new(chapter('Bad name')))
      body = book.to_rack_body # does not raise yet, the response would already be underway
      expect { body.each { |_chunk| } }.to raise_error(ZipKit::Streamer::OCFViolation, /forbidden character/)
    end
  end

  describe GEPUB::Builder do
    it 'streams the same way as the Book', :uses_temporary_directory do
      builder = GEPUB::Builder.new do
        unique_identifier 'http://example.jp/builder-streaming', 'BookID', 'URL'
        language 'en'
        title 'Streamed via Builder'
        resources do
          ordered do
            file 'text/chap1.xhtml' => StringIO.new(<<~XHTML)
              <html xmlns="http://www.w3.org/1999/xhtml"><head><title>c1</title></head><body><p>Hello</p></body></html>
            XHTML
            heading 'Chapter 1'
          end
        end
      end

      sink = ChunkCollector.new
      builder.write_epub(sink)

      rack_bytes = +''
      builder.to_rack_body.each { |chunk| rack_bytes << chunk }

      [sink.string, rack_bytes].each do |bytes|
        epub_file = @temporary_directory / 'builder.epub'
        epub_file.binwrite(bytes)
        epubcheck(epub_file)
      end
    end
  end

  describe 'writing into a ZipKit::Streamer' do
    # This is what zip_kit_stream in a Rails controller does with its block and options
    it 'writes into it instead of nesting a ZIP inside it', :uses_temporary_directory do
      book = build_book
      body = ZipKit::OutputEnumerator.new(ocf: true) { |zip| book.write_epub(zip) }
      bytes = +''
      body.each { |chunk| bytes << chunk }
      expect(bytes.byteslice(30, 8)).to eq('mimetype') # it is the first entry, not a ZIP stored inside one
      expect_valid_epub(bytes)
    end
  end
end
